// Worker entry: the Next.js app (OpenNext) plus an email handler. Bank order notices (BCR, BRD…) sent or redirected
// to the intake address (Cloudflare Email Routing → this worker) become bank orders in the CRM.
// @ts-expect-error generated by `opennextjs-cloudflare build`
import { default as app } from "./.open-next/worker.js";
import PostalMime from "postal-mime";
import { ingestBankEmail, notifyBankOrder } from "./src/lib/bank-mail";

// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

type Env = { DB: D1Database; BANK_MAIL_SENDERS?: string; BANK_MAIL_FORWARD?: string; CRM_URL?: string } & Record<string, unknown>;

/** Senders accepted on the intake address: the banks, and our own mailboxes (redirect / forward rules). */
const allowed = (env: Env, addr: string) => {
  const list = (env.BANK_MAIL_SENDERS || "bcr.ro,brd.ro,valuefy.ro").split(",").map((d) => d.trim().toLowerCase()).filter(Boolean);
  const a = addr.toLowerCase();
  return list.some((d) => a === d || a.endsWith(`@${d}`) || a.endsWith(`.${d}`));
};

/** Browsers send Origin on cross-site POSTs: an API write must come from a page of the same host (no CSRF). */
const SAFE = new Set(["GET", "HEAD", "OPTIONS"]);

export default {
  async fetch(req: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(req.url);
    if (url.pathname.startsWith("/api/") && !SAFE.has(req.method)) {
      const origin = req.headers.get("origin");
      if (origin && origin !== "null" && new URL(origin).host !== url.host) return new Response("Cerere respinsă (origine străină).", { status: 403 });
    }
    // Links in emails are built from the request host: only Cloudflare's Host counts, never client-sent forwarding
    // headers (which OpenNext would otherwise trust), so nobody can make a sign-in email point to another domain.
    const headers = new Headers(req.headers);
    headers.delete("x-forwarded-host");
    headers.delete("x-forwarded-proto");
    return app.fetch(new Request(req, { headers }), env, ctx);
  },

  async email(message: ForwardableEmailMessage, env: Env) {
    // The shared helpers read settings from process.env (as in the app).
    for (const [k, v] of Object.entries(env)) if (typeof v === "string") process.env[k] = v;
    const mail = await PostalMime.parse(await new Response(message.raw).arrayBuffer());
    const from = mail.from?.address ?? message.from;
    // The envelope sender is checked by Cloudflare (SPF); the From header alone can be forged.
    if (!allowed(env, message.from)) {
      console.log("bank-mail: ignored sender", from, message.from);
      return;
    }
    const r = await ingestBankEmail(env.DB, { from, to: message.to, subject: mail.subject ?? null, text: mail.text ?? null, html: mail.html ?? null }, "email", null);
    console.log("bank-mail:", r.status, r.notice?.bank, r.notice?.ref);
    if (r.status === "order" && r.notice && r.orderId) await notifyBankOrder(r.notice, r.orderId, env.CRM_URL || "https://crm.valuefy.ro");
    // Optional copy to a mailbox, so nothing is lost if the address is the only one receiving the notices.
    if (env.BANK_MAIL_FORWARD) await message.forward(env.BANK_MAIL_FORWARD).catch((e) => console.error("bank-mail forward", e));
  },
} satisfies ExportedHandler<Env>;
